language: rust
rust:
    - nightly
    - beta
    - stable

cache: cargo
sudo: false

script:
    - cargo build --release --examples
    - cargo test --verbose $FEATURES --no-fail-fast

notifications:
    email: false
